### ISSUE TITLE
Comments on 1st release

### ISSUE THREAD

**Issue by awegrzyn** [vladimirkosmala/FrontEndKit#1]
In general it looks really nice~!
Few comments:
- `notify()` method is not explained. Is it possible to invoke it automatically?
- `bind()` vs arrow functions
- How to scale it into large application?
- How to plug WebSockets and react on received events?
- Missing: general API reference, eg. arguments of `h()` function
- Tutorial is ok but features should be their dedicated (sub)chapters

**Comment by vladimirkosmala** [comment]
- Guide for using fetch and websocket
- Guide on how to scale
- Guide HTML new way of thinking ?
- Tests
- Firefox instructions to enable the flag of modules
- List of compatible browsers versions

**Comment by vladimirkosmala** [comment]
Documentation improved.
But tests to be seen.
